# Spring Boot application name
spring.application.name=course_analyzer

# Server port
server.port=8081

# Default active profile
spring.profiles.active=dev


# Kakao OAuth2 Settings
spring.security.oauth2.client.registration.kakao.client-id=cd8bde880bca3d17efc3511b0cd2038b
spring.security.oauth2.client.registration.kakao.client-secret=bSj1TX7Bm2UzSVoJnXZAvsTXMas6qCyU
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.scope=profile_nickname, account_email

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

